[2022-11-16 21:16:02,806] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_combustivel.pyspark_task manual__2022-11-16T21:07:34.027357+00:00 [queued]>
[2022-11-16 21:16:02,827] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: dag_combustivel.pyspark_task manual__2022-11-16T21:07:34.027357+00:00 [queued]>
[2022-11-16 21:16:02,828] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 21:16:02,829] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-11-16 21:16:02,830] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 21:16:02,859] {taskinstance.py:1264} INFO - Executing <Task(DataprocSubmitJobOperator): pyspark_task> on 2022-11-16 21:07:34.027357+00:00
[2022-11-16 21:16:02,878] {standard_task_runner.py:52} INFO - Started process 933 to run task
[2022-11-16 21:16:02,879] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_combustivel', 'pyspark_task', 'manual__2022-11-16T21:07:34.027357+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_combustivel.py', '--cfg-path', '/tmp/tmp7yuk3g23', '--error-file', '/tmp/tmpt5_cge67']
[2022-11-16 21:16:02,891] {standard_task_runner.py:77} INFO - Job 18: Subtask pyspark_task
[2022-11-16 21:16:03,053] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_combustivel.pyspark_task manual__2022-11-16T21:07:34.027357+00:00 [running]> on host b2a62e76b908
[2022-11-16 21:16:03,187] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_combustivel
AIRFLOW_CTX_TASK_ID=pyspark_task
AIRFLOW_CTX_EXECUTION_DATE=2022-11-16T21:07:34.027357+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-16T21:07:34.027357+00:00
[2022-11-16 21:16:03,189] {dataproc.py:1878} INFO - Submitting job
[2022-11-16 21:16:04,682] {dataproc.py:1890} INFO - Job c618d7d3-fc10-4024-982e-e020f52ea836 submitted successfully.
[2022-11-16 21:16:04,699] {dataproc.py:1903} INFO - Waiting for job c618d7d3-fc10-4024-982e-e020f52ea836 to complete
[2022-11-16 21:16:38,633] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 1905, in execute
    job_id=job_id, region=self.region, project_id=self.project_id, timeout=self.wait_timeout
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 433, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 780, in wait_for_job
    raise AirflowException(f'Job failed:\n{job}')
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "datapipeline-366715"
  job_id: "c618d7d3-fc10-4024-982e-e020f52ea836"
}
placement {
  cluster_name: "stack-gcp-datapipeline-clusters"
  cluster_uuid: "fa810be9-47af-4099-8993-06fd0bc8bf8f"
}
pyspark_job {
  main_python_file_uri: "gs://data-pipeline-stack-combustiveis-brasil-pyspark-code_08102022/main.py"
  args: "--path_input"
  args: "gs://data-pipeline-stack-combustiveis-brasil-raw_08102022/combustiveis-brasil/2022/02/ca-2022-02.csv"
  args: "--path_output"
  args: "gs://data-pipeline-stack-combustiveis-brasil-curated_08102022/combustiveis-brasil/2022/02/"
  args: "--file_format"
  args: "parquet"
  args: "--bq_dataset"
  args: "gasolina_brasil"
  args: "--table_bq"
  args: "tb_historico_combustivel_brasil"
  jar_file_uris: "gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.23.2.jar"
}
status {
  state: ERROR
  details: "File not found: gs://data-pipeline-stack-combustiveis-brasil-pyspark-code_08102022/main.py"
  state_start_time {
    seconds: 1668633391
    nanos: 425111000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1668633364
    nanos: 493600000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1668633364
    nanos: 552059000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1668633364
    nanos: 936513000
  }
}
driver_control_files_uri: "gs://dataproc-staging-us-central1-71488182172-qwklinpf/google-cloud-dataproc-metainfo/fa810be9-47af-4099-8993-06fd0bc8bf8f/jobs/c618d7d3-fc10-4024-982e-e020f52ea836/"
driver_output_resource_uri: "gs://dataproc-staging-us-central1-71488182172-qwklinpf/google-cloud-dataproc-metainfo/fa810be9-47af-4099-8993-06fd0bc8bf8f/jobs/c618d7d3-fc10-4024-982e-e020f52ea836/driveroutput"
job_uuid: "c618d7d3-fc10-4024-982e-e020f52ea836"
done: true

[2022-11-16 21:16:38,648] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=dag_combustivel, task_id=pyspark_task, execution_date=20221116T210734, start_date=20221116T211602, end_date=20221116T211638
[2022-11-16 21:16:38,672] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task pyspark_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 1905, in execute
    job_id=job_id, region=self.region, project_id=self.project_id, timeout=self.wait_timeout
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 433, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 780, in wait_for_job
    raise AirflowException(f'Job failed:\n{job}')
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "datapipeline-366715"
  job_id: "c618d7d3-fc10-4024-982e-e020f52ea836"
}
placement {
  cluster_name: "stack-gcp-datapipeline-clusters"
  cluster_uuid: "fa810be9-47af-4099-8993-06fd0bc8bf8f"
}
pyspark_job {
  main_python_file_uri: "gs://data-pipeline-stack-combustiveis-brasil-pyspark-code_08102022/main.py"
  args: "--path_input"
  args: "gs://data-pipeline-stack-combustiveis-brasil-raw_08102022/combustiveis-brasil/2022/02/ca-2022-02.csv"
  args: "--path_output"
  args: "gs://data-pipeline-stack-combustiveis-brasil-curated_08102022/combustiveis-brasil/2022/02/"
  args: "--file_format"
  args: "parquet"
  args: "--bq_dataset"
  args: "gasolina_brasil"
  args: "--table_bq"
  args: "tb_historico_combustivel_brasil"
  jar_file_uris: "gs://spark-lib/bigquery/spark-bigquery-with-dependencies_2.12-0.23.2.jar"
}
status {
  state: ERROR
  details: "File not found: gs://data-pipeline-stack-combustiveis-brasil-pyspark-code_08102022/main.py"
  state_start_time {
    seconds: 1668633391
    nanos: 425111000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1668633364
    nanos: 493600000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1668633364
    nanos: 552059000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1668633364
    nanos: 936513000
  }
}
driver_control_files_uri: "gs://dataproc-staging-us-central1-71488182172-qwklinpf/google-cloud-dataproc-metainfo/fa810be9-47af-4099-8993-06fd0bc8bf8f/jobs/c618d7d3-fc10-4024-982e-e020f52ea836/"
driver_output_resource_uri: "gs://dataproc-staging-us-central1-71488182172-qwklinpf/google-cloud-dataproc-metainfo/fa810be9-47af-4099-8993-06fd0bc8bf8f/jobs/c618d7d3-fc10-4024-982e-e020f52ea836/driveroutput"
job_uuid: "c618d7d3-fc10-4024-982e-e020f52ea836"
done: true

[2022-11-16 21:16:38,721] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-16 21:16:38,964] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
